import fs from "fs";
import path from "path";
import { pathToFileURL } from "url";

export interface BindingsValidationResult {
  ok: boolean;
  errors: string[];
  info: {
    vendorPath: string;
    esmEntry: string | null;
    cjsEntry: string | null;
    packageName: string | null;
    commitSha: string | null;
    expectedCommitSha: string | null;
    shaMatch: boolean | null;
    missingMethods: string[];
    missingExports: string[];
  };
}

export interface BindingsMetadata {
  expectedCommitSha?: string;
  requiredClientMethods?: string[];
  requiredExports?: string[];
}

const BINDINGS_PACKAGE_NAME = "@tevalabs/xelma-bindings";

export function getVendorBindingsRoot(cwd: string = process.cwd()): string {
  return path.resolve(cwd, "vendor", "xelma-bindings");
}

export function getMetadataPath(cwd: string = process.cwd()): string {
  return path.resolve(cwd, ".bindings-metadata.json");
}

/**
 * Load the pinned bindings metadata from .bindings-metadata.json.
 * Returns null if the file does not exist or is invalid.
 */
export function loadBindingsMetadata(
  cwd: string = process.cwd(),
): BindingsMetadata | null {
  const metaPath = getMetadataPath(cwd);
  if (!fs.existsSync(metaPath)) return null;
  try {
    const raw = fs.readFileSync(metaPath, "utf8");
    return JSON.parse(raw) as BindingsMetadata;
  } catch {
    return null;
  }
}

/**
 * Synchronous structural validation of the vendored bindings.
 * Checks file existence, package.json name, and SHA pin.
 * Does NOT check API surface — use validateVendoredBindings() for that.
 */
export function validateVendoredBindingsSync(
  cwd: string = process.cwd(),
): BindingsValidationResult {
  const vendorPath = getVendorBindingsRoot(cwd);
  const esmEntryPath = path.join(vendorPath, "dist", "index.js");
  const cjsEntryPath = path.join(vendorPath, "dist", "cjs", "index.js");
  const packageJsonPath = path.join(vendorPath, "package.json");
  const commitShaPath = path.join(vendorPath, ".commit-sha");

  const errors: string[] = [];
  let packageName: string | null = null;
  let commitSha: string | null = null;

  // --- Structural checks ---------------------------------------------------

  if (!fs.existsSync(vendorPath)) {
    errors.push(
      `vendor/xelma-bindings missing at ${vendorPath}. ` +
        "Run `npm run install-bindings` to fetch and build the bindings.",
    );
  } else {
    if (!fs.existsSync(esmEntryPath)) {
      errors.push(`ESM entry missing: ${esmEntryPath}`);
    }
    if (!fs.existsSync(cjsEntryPath)) {
      errors.push(`CJS entry missing: ${cjsEntryPath}`);
    }
    if (!fs.existsSync(packageJsonPath)) {
      errors.push(`package.json missing: ${packageJsonPath}`);
    } else {
      try {
        const pkg = JSON.parse(fs.readFileSync(packageJsonPath, "utf8"));
        packageName = typeof pkg?.name === "string" ? pkg.name : null;
        if (packageName !== BINDINGS_PACKAGE_NAME) {
          errors.push(
            `vendor package.json name is ${JSON.stringify(packageName)}, expected ${BINDINGS_PACKAGE_NAME}`,
          );
        }
      } catch (e) {
        errors.push(`vendor package.json is not valid JSON: ${(e as Error).message}`);
      }
    }
    if (fs.existsSync(commitShaPath)) {
      try {
        commitSha = fs.readFileSync(commitShaPath, "utf8").trim() || null;
      } catch {
        commitSha = null;
      }
    }
  }

  // --- Metadata / SHA pin checks -------------------------------------------

  const meta = loadBindingsMetadata(cwd);
  const expectedCommitSha = meta?.expectedCommitSha ?? null;
  let shaMatch: boolean | null = null;

  if (expectedCommitSha && expectedCommitSha !== "PLACEHOLDER") {
    if (commitSha === null) {
      errors.push(
        `Vendor .commit-sha is missing but metadata pins expected SHA ${expectedCommitSha}. ` +
          "Run `npm run install-bindings` to populate the vendor.",
      );
      shaMatch = false;
    } else if (commitSha !== expectedCommitSha) {
      errors.push(
        `Vendor commit SHA ${commitSha} does not match expected ${expectedCommitSha}. ` +
          "The vendored bindings are stale. Run `npm run install-bindings`.",
      );
      shaMatch = false;
    } else {
      shaMatch = true;
    }
  }

  return {
    ok: errors.length === 0,
    errors,
    info: {
      vendorPath,
      esmEntry: fs.existsSync(esmEntryPath) ? esmEntryPath : null,
      cjsEntry: fs.existsSync(cjsEntryPath) ? cjsEntryPath : null,
      packageName,
      commitSha,
      expectedCommitSha,
      shaMatch,
      missingMethods: [],
      missingExports: [],
    },
  };
}

/**
 * Check that the vendored bindings .d.ts file declares all required Client
 * methods. Client methods are dynamically generated by ContractSpec at
 * construction time, so they don't appear on the prototype statically.
 *
 * Returns the list of missing method names (empty array = all present).
 */
function checkClientMethodsFromDts(
  vendorPath: string,
  requiredMethods: string[],
): string[] {
  if (requiredMethods.length === 0) return [];
  const dtsPath = path.join(vendorPath, "dist", "index.d.ts");
  if (!fs.existsSync(dtsPath)) return [...requiredMethods];

  try {
    const dtsContent = fs.readFileSync(dtsPath, "utf8");
    return requiredMethods.filter(
      (m) => !dtsContent.includes(`  ${m}:`) && !dtsContent.includes(`  ${m}(`),
    );
  } catch {
    return [...requiredMethods];
  }
}

/**
 * Attempt to dynamically import the vendored bindings and verify that
 * required type/class exports are present.
 *
 * Returns the list of missing export names (empty array = all present).
 */
async function checkRequiredExports(
  vendorPath: string,
  requiredExports: string[],
  loadModule?: (esmPath: string) => Promise<Record<string, unknown>>,
): Promise<string[]> {
  if (requiredExports.length === 0) return [];
  if (!fs.existsSync(path.join(vendorPath, "dist", "index.js"))) {
    return [...requiredExports];
  }

  try {
    const esmPath = pathToFileURL(path.join(vendorPath, "dist", "index.js")).href;
    const mod = loadModule
      ? await loadModule(esmPath)
      : await import(esmPath);
    return requiredExports.filter((name) => !(name in mod));
  } catch {
    return [...requiredExports];
  }
}

/**
 * Full validation of the vendored @tevalabs/xelma-bindings package:
 * structural checks + API surface verification via dynamic import.
 *
 * Returns a structured result rather than throwing — startup callers decide
 * whether a missing vendor is fatal (Soroban-required deployments) or just
 * worth logging (API-only deployments).
 *
 * @param loadModule - Optional module loader override for testing. When
 *   provided, it is used instead of the native dynamic import(). The loader
 *   receives a file:// URL string and should return the module namespace.
 */
export async function validateVendoredBindings(
  cwd: string = process.cwd(),
  loadModule?: (esmPath: string) => Promise<Record<string, unknown>>,
): Promise<BindingsValidationResult> {
  // Run structural checks first (fast, synchronous)
  const result = validateVendoredBindingsSync(cwd);

  // If structural checks already failed, skip surface checks
  if (!result.ok) return result;

  const vendorPath = result.info.vendorPath;
  const meta = loadBindingsMetadata(cwd);

  if (!meta) return result;

  const requiredMethods = meta.requiredClientMethods ?? [];
  const requiredExports = meta.requiredExports ?? [];

  const [missingExports] = await Promise.all([
    checkRequiredExports(vendorPath, requiredExports, loadModule),
  ]);

  // Client methods are checked via .d.ts (synchronous) since they're
  // dynamically generated by ContractSpec at construction time
  const missingMethods = checkClientMethodsFromDts(vendorPath, requiredMethods);

  result.info.missingMethods = missingMethods;
  result.info.missingExports = missingExports;

  if (missingMethods.length > 0) {
    result.errors.push(
      `Client class is missing required methods: ${missingMethods.join(", ")}. ` +
        "The bindings may be from an older contract version. Run `npm run install-bindings`.",
    );
  }
  if (missingExports.length > 0) {
    result.errors.push(
      `Bindings module is missing required exports: ${missingExports.join(", ")}. ` +
        "The bindings may be from an older contract version. Run `npm run install-bindings`.",
    );
  }

  result.ok = result.errors.length === 0;
  return result;
}
